#!/bin/bash
#
# Fetches sprites from serebii.net and bundles them nicely in a
# gzipped tarball suitable for Python package data.
#
# Usage: ./fetch

cd "${BASH_SOURCE%/*}/" || exit

unset tmpdir
trap '[[ $tmpdir ]] && rm -rf "$tmpdir"' EXIT
tmpdir=$(mktemp -d)

cp "../assets/frame.png" "$tmpdir/frame.png"

pushd "$tmpdir" > /dev/null || exit

echo -n 'fetching sprites from serebii.net... 000/151'
for i in $(seq -w 151); do
  echo -n -e "\b\b\b\b\b\b\b$i/151"
  curl -s "https://www.serebii.net/pokearth/sprites/rb/$i.png" -o "$i.png"
done
echo

echo 'bundling files...'
tar cf rb.tar -- *.png
gzip rb.tar

popd > /dev/null || exit

mv "$tmpdir/rb.tar.gz" "../pkmnhof/data/rb.tar.gz"

echo 'done'
