#!/bin/bash
#
# Usage: ./fetch

cd "${BASH_SOURCE%/*}/" || exit

unset tmpdir
trap '[[ $tmpdir ]] && rm -rf "$tmpdir"' EXIT
tmpdir=$(mktemp -d)

cp "../assets/frame.png" "$tmpdir/frame.png"

pushd "$tmpdir" || exit

for i in {1..151}; do
  fmt_i=$(printf '%03d' "$i")
  echo -n "https://www.serebii.net/pokearth/sprites/rb/$fmt_i.png"
  curl -s "https://www.serebii.net/pokearth/sprites/rb/$fmt_i.png" -o "$fmt_i.png"
  echo " DONE"
done
tar cf rb.tar -- *.png
gzip rb.tar

popd || exit

mv "$tmpdir/rb.tar.gz" "../pkmnhof/data/rb.tar.gz"
